# Setup
title: Jeong Minuk
description: No pain, No gain
url: https://minukj1224.github.io
avatar: /cat.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: minukj1224
  card: summary
logo: logo.png
social:
  name: Jeong Minuk
  links:
    - https://twitter.com/minukj1224
    - https://github.com/minukj1224
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Jeong Minuk
  url: https://github.com/minukj1224/
  email: minukj1224@gmail.com
